In [ ]:

import numpy as np
import pandas as pd

**IMPORTING LIBRARIES**

In [ ]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
from itertools import cycle
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [ ]:
Monero = pd.read_csv("/content/coin_Monero (1).csv")
Monero

SNo    Name Symbol                 Date        High         Low  \
0        1  Monero    XMR  2014-05-22 23:59:59    2.188880    1.359090   
1        2  Monero    XMR  2014-05-23 23:59:59    3.434370    2.051040   
2        3  Monero    XMR  2014-05-24 23:59:59    4.014240    2.617780   
3        4  Monero    XMR  2014-05-25 23:59:59    4.043030    2.803300   
4        5  Monero    XMR  2014-05-26 23:59:59    3.762350    2.312020   
...    ...     ...    ...                  ...         ...         ...   
2597  2598  Monero    XMR  2021-07-02 23:59:59  211.666077  199.608531   
2598  2599  Monero    XMR  2021-07-03 23:59:59  216.327967  207.042192   
2599  2600  Monero    XMR  2021-07-04 23:59:59  224.909012  213.023069   
2600  2601  Monero    XMR  2021-07-05 23:59:59  220.354191  206.502607   
2601  2602  Monero    XMR  2021-07-06 23:59:59  222.137136  212.296827   

            Open       Close        Volume     Marketcap  
0       1.589400    2.095580  1.329180e+05  1.855608e+06  
1       2.051040    2.963020  2.668520e+05  2.692180e+06  
2       2.920390    3.702450  2.480280e+05  3.456658e+06  
3       4.043030    3.138560  2.835450e+05  2.993339e+06  
4       3.218970    3.021860  2.201480e+05  2.946133e+06  
...          ...         ...           ...           ...  
2597  206.252403  211.345143  1.519434e+08  3.792466e+09  
2598  211.458163  214.752778  1.364141e+08  3.853768e+09  
2599  214.839958  219.841418  1.697858e+08  3.945232e+09  
2600  219.961957  214.464993  1.709852e+08  3.848898e+09  
2601  214.470724  222.137136  1.678620e+08  3.986738e+09  

[2602 rows x 10 columns]

**ETHEREUM**

Ethereum is a platform powered by blockchain technology that is best known for its native cryptocurrency, called ether, or ETH, or simply ethereum. The distributed nature of blockchain technology is what makes the Ethereum platform secure, and that security enables ETH to accrue value.

In [ ]:
Ethereum = pd.read_csv("/content/coin_Ethereum (1).csv")
Ethereum

SNo      Name Symbol                 Date         High          Low  \
0        1  Ethereum    ETH  2015-08-08 23:59:59     2.798810     0.714725   
1        2  Ethereum    ETH  2015-08-09 23:59:59     0.879810     0.629191   
2        3  Ethereum    ETH  2015-08-10 23:59:59     0.729854     0.636546   
3        4  Ethereum    ETH  2015-08-11 23:59:59     1.131410     0.663235   
4        5  Ethereum    ETH  2015-08-12 23:59:59     1.289940     0.883608   
...    ...       ...    ...                  ...          ...          ...   
2155  2156  Ethereum    ETH  2021-07-02 23:59:59  2155.596496  2021.824808   
2156  2157  Ethereum    ETH  2021-07-03 23:59:59  2237.567155  2117.590013   
2157  2158  Ethereum    ETH  2021-07-04 23:59:59  2384.286857  2190.837703   
2158  2159  Ethereum    ETH  2021-07-05 23:59:59  2321.922836  2163.041394   
2159  2160  Ethereum    ETH  2021-07-06 23:59:59  2346.294874  2197.919385   

             Open        Close        Volume     Marketcap  
0        2.793760     0.753325  6.741880e+05  4.548689e+07  
1        0.706136     0.701897  5.321700e+05  4.239957e+07  
2        0.713989     0.708448  4.052830e+05  4.281836e+07  
3        0.708087     1.067860  1.463100e+06  6.456929e+07  
4        1.058750     1.217440  2.150620e+06  7.364501e+07  
...           ...          ...           ...           ...  
2155  2109.892677  2150.040364  3.179621e+10  2.505527e+11  
2156  2150.835025  2226.114282  1.743336e+10  2.594475e+11  
2157  2226.550382  2321.724112  1.878711e+10  2.706217e+11  
2158  2321.922836  2198.582464  2.010379e+10  2.562978e+11  
2159  2197.919385  2324.679449  2.089186e+10  2.710286e+11  

[2160 rows x 10 columns]

**WRAPPED BITCOIN**

Wrapped Bitcoin is a digital token  that represents a cryptocurrency from another blockchain or token standard and is worth the same as the original cryptocurrency. Unlike the original cryptocurrency, the wrapped token can be used on certain non-native blockchains and later redeemed for the original cryptocurrency.

In [ ]:
WrappedBitcoin = pd.read_csv("/content/coin_WrappedBitcoin (1).csv")
WrappedBitcoin

SNo             Name Symbol                 Date          High  \
0      1  Wrapped Bitcoin   WBTC  2019-01-31 23:59:59   3535.421222   
1      2  Wrapped Bitcoin   WBTC  2019-02-01 23:59:59   3517.770253   
2      3  Wrapped Bitcoin   WBTC  2019-02-02 23:59:59   3546.404225   
3      4  Wrapped Bitcoin   WBTC  2019-02-03 23:59:59   3544.667094   
4      5  Wrapped Bitcoin   WBTC  2019-02-04 23:59:59   3500.410630   
..   ...              ...    ...                  ...           ...   
883  884  Wrapped Bitcoin   WBTC  2021-07-02 23:59:59  33841.008754   
884  885  Wrapped Bitcoin   WBTC  2021-07-03 23:59:59  34871.130346   
885  886  Wrapped Bitcoin   WBTC  2021-07-04 23:59:59  35914.361323   
886  887  Wrapped Bitcoin   WBTC  2021-07-05 23:59:59  35294.411111   
887  888  Wrapped Bitcoin   WBTC  2021-07-06 23:59:59  35004.772491   

              Low          Open         Close        Volume     Marketcap  
0     3435.290530   3496.839832   3466.506533  1.928907e+04  0.000000e+00  
1     3422.825563   3469.392973   3480.772314  1.364047e+04  0.000000e+00  
2     3459.112772   3476.335119   3542.095361  1.894967e+03  0.000000e+00  
3     3436.177705   3540.562788   3477.866026  6.524925e+03  0.000000e+00  
4     3445.643244   3481.734248   3481.219346  3.540939e+03  0.000000e+00  
..            ...           ...           ...           ...           ...  
883  32761.826975  33529.259522  33824.263339  1.609147e+08  6.625345e+09  
884  33381.245301  33806.037094  34676.985915  1.659959e+08  6.792373e+09  
885  34382.512697  34672.651028  35289.762931  1.583060e+08  6.912401e+09  
886  33288.379267  35294.411111  33806.661764  1.711673e+08  6.621898e+09  
887  33700.560335  33772.552729  34189.372826  2.035448e+08  6.713947e+09  

[888 rows x 10 columns]

**BITCOIN**

Bitcoin is a digital currency which operates free of any central control or the oversight of banks or governments. Instead it relies on peer-to-peer software and cryptography. A public ledger records all bitcoin transactions and copies are held on servers around the world.

In [ ]:
Bitcoin = pd.read_csv("/content/coin_Bitcoin (1).csv")
Bitcoin

SNo     Name Symbol            Date          High           Low  \
0        1  Bitcoin    BTC  29-04-13 23:59    147.488007    134.000000   
1        2  Bitcoin    BTC  30-04-13 23:59    146.929993    134.050003   
2        3  Bitcoin    BTC  01-05-13 23:59    139.889999    107.720001   
3        4  Bitcoin    BTC  02-05-13 23:59    125.599998     92.281898   
4        5  Bitcoin    BTC  03-05-13 23:59    108.127998     79.099998   
...    ...      ...    ...             ...           ...           ...   
2986  2987  Bitcoin    BTC  02-07-21 23:59  33939.588700  32770.680780   
2987  2988  Bitcoin    BTC  03-07-21 23:59  34909.259900  33402.696540   
2988  2989  Bitcoin    BTC  04-07-21 23:59  35937.567150  34396.477460   
2989  2990  Bitcoin    BTC  05-07-21 23:59  35284.344430  33213.661030   
2990  2991  Bitcoin    BTC  06-07-21 23:59  35038.536360  33599.916170   

              Open         Close        Volume     Marketcap  
0       134.444000    144.539993  1.329180e+05  1.603769e+09  
1       144.000000    139.000000  2.668520e+05  1.542813e+09  
2       139.000000    116.989998  2.480280e+05  1.298955e+09  
3       116.379997    105.209999  2.835450e+05  1.168517e+09  
4       106.250000     97.750000  2.201480e+05  1.085995e+09  
...            ...           ...           ...           ...  
2986  33549.600180  33897.048590  3.872897e+10  6.354510e+11  
2987  33854.421360  34668.548400  2.438396e+10  6.499400e+11  
2988  34665.564870  35287.779770  2.492431e+10  6.615750e+11  
2989  35284.344430  33746.002460  2.672155e+10  6.326960e+11  
2990  33723.509660  34235.193450  2.650126e+10  6.418990e+11  

[2991 rows x 10 columns]

**CREATION OF A TARGET COLUMN**

* Creation of a variable for predicting 'N' days out into the future(here, let us assume N = 5).

* Creation of a new column with a name Prediction.





In [ ]:
################################################### Monero #############################################################
#Creation of a variable for predicting '5' days out into the future
projection_Monero = 5

#creation of a new column with a name prediction
Monero['Prediction'] = Monero[['Close']].shift(-projection_Monero)
Monero

SNo    Name Symbol                 Date        High         Low  \
0        1  Monero    XMR  2014-05-22 23:59:59    2.188880    1.359090   
1        2  Monero    XMR  2014-05-23 23:59:59    3.434370    2.051040   
2        3  Monero    XMR  2014-05-24 23:59:59    4.014240    2.617780   
3        4  Monero    XMR  2014-05-25 23:59:59    4.043030    2.803300   
4        5  Monero    XMR  2014-05-26 23:59:59    3.762350    2.312020   
...    ...     ...    ...                  ...         ...         ...   
2597  2598  Monero    XMR  2021-07-02 23:59:59  211.666077  199.608531   
2598  2599  Monero    XMR  2021-07-03 23:59:59  216.327967  207.042192   
2599  2600  Monero    XMR  2021-07-04 23:59:59  224.909012  213.023069   
2600  2601  Monero    XMR  2021-07-05 23:59:59  220.354191  206.502607   
2601  2602  Monero    XMR  2021-07-06 23:59:59  222.137136  212.296827   

            Open       Close        Volume     Marketcap  Prediction  
0       1.589400    2.095580  1.329180e+05  1.855608e+06     2.20823  
1       2.051040    2.963020  2.668520e+05  2.692180e+06     2.26886  
2       2.920390    3.702450  2.480280e+05  3.456658e+06     1.67653  
3       4.043030    3.138560  2.835450e+05  2.993339e+06     1.56764  
4       3.218970    3.021860  2.201480e+05  2.946133e+06     1.93854  
...          ...         ...           ...           ...         ...  
2597  206.252403  211.345143  1.519434e+08  3.792466e+09         NaN  
2598  211.458163  214.752778  1.364141e+08  3.853768e+09         NaN  
2599  214.839958  219.841418  1.697858e+08  3.945232e+09         NaN  
2600  219.961957  214.464993  1.709852e+08  3.848898e+09         NaN  
2601  214.470724  222.137136  1.678620e+08  3.986738e+09         NaN  

[2602 rows x 11 columns]

In [ ]:
################################################### Ethereum #############################################################
#Creation of a variable for predicting '5' days out into the future
projection_Ethereum = 5
#creation of a new column with a name prediction
Ethereum['Prediction'] = Ethereum[['Close']].shift(-projection_Ethereum)
Ethereum

SNo      Name Symbol                 Date         High          Low  \
0        1  Ethereum    ETH  2015-08-08 23:59:59     2.798810     0.714725   
1        2  Ethereum    ETH  2015-08-09 23:59:59     0.879810     0.629191   
2        3  Ethereum    ETH  2015-08-10 23:59:59     0.729854     0.636546   
3        4  Ethereum    ETH  2015-08-11 23:59:59     1.131410     0.663235   
4        5  Ethereum    ETH  2015-08-12 23:59:59     1.289940     0.883608   
...    ...       ...    ...                  ...          ...          ...   
2155  2156  Ethereum    ETH  2021-07-02 23:59:59  2155.596496  2021.824808   
2156  2157  Ethereum    ETH  2021-07-03 23:59:59  2237.567155  2117.590013   
2157  2158  Ethereum    ETH  2021-07-04 23:59:59  2384.286857  2190.837703   
2158  2159  Ethereum    ETH  2021-07-05 23:59:59  2321.922836  2163.041394   
2159  2160  Ethereum    ETH  2021-07-06 23:59:59  2346.294874  2197.919385   

             Open        Close        Volume     Marketcap  Prediction  
0        2.793760     0.753325  6.741880e+05  4.548689e+07     1.82767  
1        0.706136     0.701897  5.321700e+05  4.239957e+07     1.82787  
2        0.713989     0.708448  4.052830e+05  4.281836e+07     1.68890  
3        0.708087     1.067860  1.463100e+06  6.456929e+07     1.56603  
4        1.058750     1.217440  2.150620e+06  7.364501e+07     1.20361  
...           ...          ...           ...           ...         ...  
2155  2109.892677  2150.040364  3.179621e+10  2.505527e+11         NaN  
2156  2150.835025  2226.114282  1.743336e+10  2.594475e+11         NaN  
2157  2226.550382  2321.724112  1.878711e+10  2.706217e+11         NaN  
2158  2321.922836  2198.582464  2.010379e+10  2.562978e+11         NaN  
2159  2197.919385  2324.679449  2.089186e+10  2.710286e+11         NaN  

[2160 rows x 11 columns]

In [ ]:
################################################### WrappedBitcoin #############################################################
#Creation of a variable for predicting '5' days out into the future
projection_WrappedBitcoin = 5
#creation of a new column with a name prediction
WrappedBitcoin['Prediction'] = WrappedBitcoin[['Close']].shift(-projection_WrappedBitcoin)
WrappedBitcoin

SNo             Name Symbol                 Date          High  \
0      1  Wrapped Bitcoin   WBTC  2019-01-31 23:59:59   3535.421222   
1      2  Wrapped Bitcoin   WBTC  2019-02-01 23:59:59   3517.770253   
2      3  Wrapped Bitcoin   WBTC  2019-02-02 23:59:59   3546.404225   
3      4  Wrapped Bitcoin   WBTC  2019-02-03 23:59:59   3544.667094   
4      5  Wrapped Bitcoin   WBTC  2019-02-04 23:59:59   3500.410630   
..   ...              ...    ...                  ...           ...   
883  884  Wrapped Bitcoin   WBTC  2021-07-02 23:59:59  33841.008754   
884  885  Wrapped Bitcoin   WBTC  2021-07-03 23:59:59  34871.130346   
885  886  Wrapped Bitcoin   WBTC  2021-07-04 23:59:59  35914.361323   
886  887  Wrapped Bitcoin   WBTC  2021-07-05 23:59:59  35294.411111   
887  888  Wrapped Bitcoin   WBTC  2021-07-06 23:59:59  35004.772491   

              Low          Open         Close        Volume     Marketcap  \
0     3435.290530   3496.839832   3466.506533  1.928907e+04  0.000000e+00   
1     3422.825563   3469.392973   3480.772314  1.364047e+04  0.000000e+00   
2     3459.112772   3476.335119   3542.095361  1.894967e+03  0.000000e+00   
3     3436.177705   3540.562788   3477.866026  6.524925e+03  0.000000e+00   
4     3445.643244   3481.734248   3481.219346  3.540939e+03  0.000000e+00   
..            ...           ...           ...           ...           ...   
883  32761.826975  33529.259522  33824.263339  1.609147e+08  6.625345e+09   
884  33381.245301  33806.037094  34676.985915  1.659959e+08  6.792373e+09   
885  34382.512697  34672.651028  35289.762931  1.583060e+08  6.912401e+09   
886  33288.379267  35294.411111  33806.661764  1.711673e+08  6.621898e+09   
887  33700.560335  33772.552729  34189.372826  2.035448e+08  6.713947e+09   

      Prediction  
0    3461.872926  
1    3444.961049  
2    3395.978616  
3    3664.841137  
4    3677.963979  
..           ...  
883          NaN  
884          NaN  
885          NaN  
886          NaN  
887          NaN  

[888 rows x 11 columns]

In [ ]:
################################################### Bitcoin #############################################################
#Creation of a variable for predicting '5' days out into the future
projection_Bitcoin = 5
#creation of a new column with a name prediction
Bitcoin['Prediction'] = Bitcoin[['Close']].shift(-projection_Bitcoin)
Bitcoin

SNo     Name Symbol            Date          High           Low  \
0        1  Bitcoin    BTC  29-04-13 23:59    147.488007    134.000000   
1        2  Bitcoin    BTC  30-04-13 23:59    146.929993    134.050003   
2        3  Bitcoin    BTC  01-05-13 23:59    139.889999    107.720001   
3        4  Bitcoin    BTC  02-05-13 23:59    125.599998     92.281898   
4        5  Bitcoin    BTC  03-05-13 23:59    108.127998     79.099998   
...    ...      ...    ...             ...           ...           ...   
2986  2987  Bitcoin    BTC  02-07-21 23:59  33939.588700  32770.680780   
2987  2988  Bitcoin    BTC  03-07-21 23:59  34909.259900  33402.696540   
2988  2989  Bitcoin    BTC  04-07-21 23:59  35937.567150  34396.477460   
2989  2990  Bitcoin    BTC  05-07-21 23:59  35284.344430  33213.661030   
2990  2991  Bitcoin    BTC  06-07-21 23:59  35038.536360  33599.916170   

              Open         Close        Volume     Marketcap  Prediction  
0       134.444000    144.539993  1.329180e+05  1.603769e+09  112.500000  
1       144.000000    139.000000  2.668520e+05  1.542813e+09  115.910004  
2       139.000000    116.989998  2.480280e+05  1.298955e+09  112.300003  
3       116.379997    105.209999  2.835450e+05  1.168517e+09  111.500000  
4       106.250000     97.750000  2.201480e+05  1.085995e+09  113.566002  
...            ...           ...           ...           ...         ...  
2986  33549.600180  33897.048590  3.872897e+10  6.354510e+11         NaN  
2987  33854.421360  34668.548400  2.438396e+10  6.499400e+11         NaN  
2988  34665.564870  35287.779770  2.492431e+10  6.615750e+11         NaN  
2989  35284.344430  33746.002460  2.672155e+10  6.326960e+11         NaN  
2990  33723.509660  34235.193450  2.650126e+10  6.418990e+11         NaN  

[2991 rows x 11 columns]

**DATA VISUALIZATION**

In [ ]:
################################################### Monero #############################################################
visualize_Monero = cycle(['Open','Close','High','Low','Prediction'])

fig = px.line(Monero, x=Monero.Date, y=[Monero['Open'], Monero['Close'],
                                          Monero['High'], Monero['Low'], Monero['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig.update_layout(title_text='Monero', font_size=15, font_color='black',legend_title_text='Parameters')
fig.for_each_trace(lambda t:  t.update(name = next(visualize_Monero)))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [ ]:
################################################### Ethereum #############################################################
visualize_Ethereum = cycle(['Open','Close','High','Low','Prediction'])

fig = px.line(Ethereum, x=Ethereum.Date, y=[Ethereum['Open'], Ethereum['Close'],
                                          Ethereum['High'], Ethereum['Low'],Ethereum['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig.update_layout(title_text='Ethereum', font_size=15, font_color='black',legend_title_text='Parameters')
fig.for_each_trace(lambda t:  t.update(name = next(visualize_Ethereum)))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [ ]:
################################################### WrappedBitcoin #############################################################
visualize_WrappedBitcoin = cycle(['Open','Close','High','Low','Prediction'])

fig = px.line(WrappedBitcoin, x=WrappedBitcoin.Date, y=[WrappedBitcoin['Open'], WrappedBitcoin['Close'],
                                          WrappedBitcoin['High'], WrappedBitcoin['Low'],WrappedBitcoin['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig.update_layout(title_text='WrappedBitcoin', font_size=15, font_color='black',legend_title_text='Parameters')
fig.for_each_trace(lambda t:  t.update(name = next(visualize_WrappedBitcoin)))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [ ]:
################################################### Bitcoin #############################################################
visualize_Bitcoin = cycle(['Open','Close','High','Low','Prediction'])

fig = px.line(Bitcoin, x=Bitcoin.Date, y=[Bitcoin['Open'], Bitcoin['Close'],
                                          Bitcoin['High'], Bitcoin['Low'],Bitcoin['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig.update_layout(title_text='Bitcoin', font_size=15, font_color='black',legend_title_text='Parameters')
fig.for_each_trace(lambda t:  t.update(name = next(visualize_Bitcoin)))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

**CREATION OF THE INDEPENDENT DATA SET(X) & DEPENDENT DATA SET(y)**

In [ ]:
################################################### Monero #############################################################

In [ ]:
#Creation of the independent data set (X)
X_Monero = np.array(Monero[['Close']])
X_Monero = X_Monero[:-projection_Monero]
print(X_Monero)

[[  2.0955801 ]
 [  2.96302009]
 [  3.70245004]
 ...
 [217.1449805 ]
 [222.2694386 ]
 [206.56387428]]


In [ ]:
#creation of the dependent data set (y)
y_Monero = Monero['Prediction'].values
y_Monero = y_Monero[:-projection_Monero]
print(y_Monero)

[  2.20823002   2.2688601    1.67653    ... 219.84141793 214.46499257
 222.13713561]


In [ ]:
################################################### Ethereum #############################################################

In [ ]:
#Creation of the independent data set (X)
X_Ethereum = np.array(Ethereum[['Close']])
X_Ethereum = X_Ethereum[:-projection_Ethereum]
print(X_Ethereum)

[[7.53324986e-01]
 [7.01897025e-01]
 [7.08447993e-01]
 ...
 [2.16076835e+03]
 [2.27454771e+03]
 [2.11360552e+03]]


In [ ]:
#creation of the dependent data set (y)
y_Ethereum = Ethereum['Prediction'].values
y_Ethereum = y_Ethereum[:-projection_Ethereum]
print(y_Ethereum)

[1.82766998e+00 1.82787001e+00 1.68889999e+00 ... 2.32172411e+03
 2.19858246e+03 2.32467945e+03]


In [ ]:
################################################### WrappedBitcoin #############################################################

In [ ]:
#Creation of the independent data set (X)
X_WrappedBitcoin = np.array(WrappedBitcoin[['Close']])
X_WrappedBitcoin = X_WrappedBitcoin[:-projection_WrappedBitcoin]
print(X_WrappedBitcoin)

[[ 3466.50653268]
 [ 3480.77231412]
 [ 3542.09536095]
 [ 3477.86602633]
 [ 3481.21934559]
 [ 3461.8729256 ]
 [ 3444.96104912]
 [ 3395.9786162 ]
 [ 3664.8411371 ]
 [ 3677.96397919]
 [ 3686.28802728]
 [ 3636.48735917]
 [ 3664.99121582]
 [ 3641.11856305]
 [ 3611.82446599]
 [ 3629.19582092]
 [ 3644.54475489]
 [ 3705.2908502 ]
 [ 3909.03267156]
 [ 3869.74387065]
 [ 4055.46445129]
 [ 3978.72447272]
 [ 4018.18880002]
 [ 4166.84249427]
 [ 3659.92785254]
 [ 3865.78174586]
 [ 3904.57309629]
 [ 3903.79497581]
 [ 3854.58555645]
 [ 3858.34984195]
 [ 3871.57692662]
 [ 3824.16926661]
 [ 3759.72220956]
 [ 3923.0371054 ]
 [ 3923.13054144]
 [ 3898.29963424]
 [ 3901.64382424]
 [ 3941.1867382 ]
 [ 3979.81068069]
 [ 3900.04842514]
 [ 3909.91919298]
 [ 3901.74356101]
 [ 3941.65341835]
 [ 3967.20486186]
 [ 4041.24493155]
 [ 4031.44661696]
 [ 4075.62411073]
 [ 4076.27262813]
 [ 4102.37682654]
 [ 4031.06209408]
 [ 4034.86531636]
 [ 4043.71893913]
 [ 4034.19217595]
 [ 3974.14404654]
 [ 3991.63232287]
 [ 4083.73

In [ ]:
#creation of the dependent data set (y)
y_WrappedBitcoin = WrappedBitcoin['Prediction'].values
y_WrappedBitcoin = y_WrappedBitcoin[:-projection_WrappedBitcoin]
print(y_WrappedBitcoin)

[ 3461.8729256   3444.96104912  3395.9786162   3664.8411371
  3677.96397919  3686.28802728  3636.48735917  3664.99121582
  3641.11856305  3611.82446599  3629.19582092  3644.54475489
  3705.2908502   3909.03267156  3869.74387065  4055.46445129
  3978.72447272  4018.18880002  4166.84249427  3659.92785254
  3865.78174586  3904.57309629  3903.79497581  3854.58555645
  3858.34984195  3871.57692662  3824.16926661  3759.72220956
  3923.0371054   3923.13054144  3898.29963424  3901.64382424
  3941.1867382   3979.81068069  3900.04842514  3909.91919298
  3901.74356101  3941.65341835  3967.20486186  4041.24493155
  4031.44661696  4075.62411073  4076.27262813  4102.37682654
  4031.06209408  4034.86531636  4043.71893913  4034.19217595
  3974.14404654  3991.63232287  4083.73683816  4085.97603903
  4097.39383886  4100.34604631  4101.25067159  4144.11904434
  4898.99467254  4999.96133758  4903.40752198  5042.6092631
  5076.99428277  5209.29143145  5244.83335988  5205.6787486
  5283.3693789   5093.40394

In [ ]:
X_Bitcoin = np.array(Bitcoin[['Close']])
X_Bitcoin = X_Bitcoin[:-projection_Bitcoin]
print(X_Bitcoin)

[[  144.5399933]
 [  139.       ]
 [  116.9899979]
 ...
 [35867.77774  ]
 [35040.83725  ]
 [33572.11765  ]]


In [ ]:
y_Bitcoin = Bitcoin['Prediction'].values
y_Bitcoin = y_Bitcoin[:-projection_Bitcoin]
print(y_Bitcoin)

[  112.5         115.9100037   112.3000031 ... 35287.77977   33746.00246
 34235.19345  ]


**SPLIT THE DATA INTO 85% TRAINING & 15% TESTING DATA SETS**

In [ ]:
################################################### Monero #############################################################
x_train_Monero, x_test_Monero, y_train_Monero, y_test_Monero = train_test_split(X_Monero,y_Monero,test_size=0.15)

In [ ]:
################################################### Ethereum #############################################################
x_train_Ethereum, x_test_Ethereum, y_train_Ethereum, y_test_Ethereum = train_test_split(X_Ethereum,y_Ethereum,test_size=0.15)

In [ ]:
################################################### WrappedBitcoin #############################################################
x_train_WrappedBitcoin, x_test_WrappedBitcoin, y_train_WrappedBitcoin, y_test_WrappedBitcoin = train_test_split(X_WrappedBitcoin,y_WrappedBitcoin,test_size=0.15)

In [ ]:
################################################### Bitcoin #############################################################
x_train_Bitcoin, x_test_Bitcoin, y_train_Bitcoin, y_test_Bitcoin = train_test_split(X_Bitcoin,y_Bitcoin,test_size=0.15)

**CREATE & TRAIN THE MODEL : LINEAR REGRESSION**

Linear-regression models have become a proven way to scientifically and reliably predict the future. Because linear regression is a long-established statistical procedure, the properties of linear-regression models are well understood and can be trained very quickly.

In [ ]:
################################################### Monero #############################################################
#create & train the model
linReg_Monero = LinearRegression()
linReg_Monero.fit(x_train_Monero,y_train_Monero)

LinearRegression()

In [ ]:
################################################### Ethereum #############################################################
linReg_Ethereum = LinearRegression()
linReg_Ethereum.fit(x_train_Ethereum,y_train_Ethereum)

LinearRegression()

In [ ]:
################################################### WrappedBitcoin #############################################################
linReg_WrappedBitcoin = LinearRegression()
linReg_WrappedBitcoin.fit(x_train_WrappedBitcoin,y_train_WrappedBitcoin)

LinearRegression()

In [ ]:
################################################### Bitcoin #############################################################
linReg_Bitcoin = LinearRegression()
linReg_Bitcoin.fit(x_train_Bitcoin,y_train_Bitcoin)

LinearRegression()

**EVALUATION**

* Test the model using score which returns the coefficient of determination "R squared" of the prediction.

* R squared coefficient of determination is a statistical measure of how well the regression predictions approximate the real data points.

* In statistics, the coefficient of determination, denoted R2 or r2 and pronounced "R squared", is the proportion of the variation in the dependent variable that is predictable from the independent variable(s).

In [ ]:
################################################### Monero #############################################################
linReg_confidence_Monero = linReg_Monero.score(x_test_Monero,y_test_Monero)
print("Accuracy by using Linear Regression Confidence for Monero: ",linReg_confidence_Monero)
print(linReg_confidence_Monero*100,'%')

Accuracy by using Linear Regression Confidence for Monero:  0.9648701034685755
96.48701034685755 %


In [ ]:
################################################### Ethereum #############################################################
linReg_confidence_Ethereum = linReg_Ethereum.score(x_test_Ethereum,y_test_Ethereum)
print("Accuracy by using Linear Regression Confidence for Ethereum: ",linReg_confidence_Ethereum)
print(linReg_confidence_Ethereum*100,'%')

Accuracy by using Linear Regression Confidence for Ethereum:  0.9776207023217636
97.76207023217636 %


In [ ]:
################################################### WrappedBitcoin #############################################################
linReg_confidence_WrappedBitcoin = linReg_WrappedBitcoin.score(x_test_WrappedBitcoin,y_test_WrappedBitcoin)
print("Accuracy by using Linear Regression Confidence for WrappedBitcoin: ",linReg_confidence_WrappedBitcoin)
print(linReg_confidence_WrappedBitcoin*100,'%')

Accuracy by using Linear Regression Confidence for WrappedBitcoin:  0.9769882578131305
97.69882578131305 %


In [ ]:
################################################### Bitcoin #############################################################
linReg_confidence_Bitcoin = linReg_Bitcoin.score(x_test_Bitcoin,y_test_Bitcoin)
print("Linear Regression Confidence for Bitcoin: ",linReg_confidence_Bitcoin)
print(linReg_confidence_Bitcoin*100,'%')

Linear Regression Confidence for Bitcoin:  0.9811133623903356
98.11133623903356 %


**LINEAR REGRESSION MODELS PREDICTION FOR THE NEXT 'N' DAYS**

* Creation of a variable called x_projection_coin & set it equal to the last 5 rows of data from the original dataset.

* Print the linear regression models predictions for the next 5 days(here, N=5).


In [ ]:
################################################### Monero #############################################################

In [ ]:
x_projection_Monero = np.array(Monero[['Close']])[-projection_Monero:]
print(x_projection_Monero)

[[211.34514337]
 [214.75277811]
 [219.84141793]
 [214.46499257]
 [222.13713561]]


In [ ]:
linReg_prediction_Monero = linReg_Monero.predict(x_projection_Monero)
print(linReg_prediction_Monero)

[208.91920898 212.25991823 217.24861785 211.97778476 219.49924794]


In [ ]:
################################################### Ethereum #############################################################

In [ ]:
x_projection_Ethereum = np.array(Ethereum[['Close']])[-projection_Ethereum:]
print(x_projection_Ethereum)

[[2150.04036404]
 [2226.11428196]
 [2321.72411157]
 [2198.58246387]
 [2324.67944917]]


In [ ]:
linReg_prediction_Ethereum = linReg_Ethereum.predict(x_projection_Ethereum)
print(linReg_prediction_Ethereum)

[2141.7226965  2217.21843179 2312.1016005  2189.89586307 2315.03447672]


In [ ]:
################################################### WrappedBitcoin #############################################################

In [ ]:
x_projection_WrappedBitcoin = np.array(WrappedBitcoin[['Close']])[-projection_WrappedBitcoin:]
print(x_projection_WrappedBitcoin)

[[33824.2633391 ]
 [34676.98591455]
 [35289.76293143]
 [33806.66176437]
 [34189.37282594]]


In [ ]:
linReg_prediction_WrappedBitcoin = linReg_WrappedBitcoin.predict(x_projection_WrappedBitcoin)
print(linReg_prediction_WrappedBitcoin)

[33914.04298194 34761.79665774 35371.00296171 33896.54397335
 34277.02493932]


In [ ]:
################################################### Bitcoin #############################################################

In [ ]:
x_projection_Bitcoin = np.array(Bitcoin[['Close']])[-projection_Bitcoin:]
print(x_projection_Bitcoin)

[[33897.04859]
 [34668.5484 ]
 [35287.77977]
 [33746.00246]
 [34235.19345]]


In [ ]:
  linReg_prediction_Bitcoin = linReg_Bitcoin.predict(x_projection_Bitcoin)
  print(linReg_prediction_Bitcoin)

[33978.82924434 34750.85392314 35370.50657027 33827.68035423
 34317.20415195]


**INFERENCE**

* Linear Regression Confidence for Monero:  0.9655124595738546

* Linear Regression Confidence for Ethereum:  0.9746703970582931

* Linear Regression Confidence for WrappedBitcoin:  0.976342650058272

* Linear Regression Confidence for Bitcoin:  0.9852120347748419


**CONCLUSION**

* Linear regression model's predictions for the next 5 days from the Monero data given here is [209.22034045 212.56636304 217.5629971  212.28378084 219.81720678]

* Linear regression model's predictions for the next 5 days from the Ethereum given here is [2150.08096162 2225.93127902 2321.26008712 2198.48038392 2324.20673824]

* Linear regression model's predictions for the next 5 days from the WrappedBitcoin given here is [33984.41615247 34833.76298282 35444.11414741 33966.88425858
 34348.08024945]

* Linear regression model's predictions for the next 5 days from the Bitcoin given here is [34002.65397578 34775.34701974 35395.53611152 33851.37422844
 34341.32182538]





**According to Satoshi Nakamolo, "Start the day with coffee, end the day with cryptocurrency "**

Hence, in this notebook we have successfully predicted the cryptocurrency pricing movements especially for Monero, Ethereum, Wrapped Bitcoin & Bitcoin using Linear Regression.